### ISSUE TITLE
Fix orange Travis tests

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_python#4]
Travis tests that were previously passing are now failing on same build (see [#47](https://travis-ci.org/OpenAgInitiative/openag_python/builds/156251362), [#45](https://travis-ci.org/OpenAgInitiative/openag_python/builds/155353200) build history).

I think the problem is with codegen?

**Comment by LeonChambers** [comment]
I suspect the build broke due to changes in repositories that the tests
depend on. Haven't looked into it yet though, so I'm not sure.

**Comment by LeonChambers** [comment]
Looks like the 3.0 release of platformio a little over a week ago broke our build. In the short term, I'll update the travis build to use 2.0. In the long term, I'll try to figure out what changed and how to become compatible with it.

**Comment by LeonChambers** [comment]
Works for now
