### ISSUE TITLE
Default value for --api_url is missing

### ISSUE THREAD

**Issue by serein7** [OpenAgInitiative/openag_python#5]
As a follow up to this [thread](https://github.com/OpenAgInitiative/openag_brain_install_rpi/issues/2):

If there is no -A is given to main script of `openag_brains`, then, in turn, no `--api_url` param is passed to `openag db init` and no default value set in `init.py` and couchdb proxy is not setup.

Is there a special reason for such this or I can create a PR with adding default value to `@click.option("--api_url", default="http://localhost:5000")` ?

**Comment by LeonChambers** [comment]
This default should be set in `openag_brain`, not `openag_python`. `openag_python` doesn't assume that you're using the ROS stack, so it can't assume that there is an API to proxy at all.

**Comment by serein7** [comment]
Ok, makes sense. Here we go https://github.com/OpenAgInitiative/openag_brain/pull/51
